PapuGO/
│── .github/
│   ├── workflows/
│   │   ├── deploy-backend.yml
│── app.py
│── requirements.txt
│── Dockerfile

name: Deploy Backend to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/papugo/food-backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy food-backend \
            --image gcr.io/papugo/food-backend \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated
